modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "FlooferLand"
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "${minecraft_range}"
type = "required"
